---
- name: Install torrent packages
  apt: "name={{item}} state=present"
  with_items:
    - rtorrent

- name: Create config for rtorrent
  template:
    src: ".rtorrent.rc.j2"
    dest: "/home/{{ user }}/.rtorrent.rc"


- name: Import rtorrent.service
  template:
    src: rtorrent.service.j2
    dest: /etc/systemd/system/rtorrent.service
    force: yes

- name: Start rtorrent service
  systemd: 
    enabled: yes
    name: rtorrent 
    daemon_reload: yes 