---
- hosts: all
  become: true
  vars:
    ci: False
  vars_files:
    - vars.yml
  roles:
    - dependencies
    - plexdrive
    - rclone
    - unionfs
    - radarr
    - sonarr
    - jackett
    - plex
    - transmission
    - traefik
    - ufw
    