---
- name: Download plex-claim
  template:
    src: "plex-claim-server.sh"
    dest: /tmp/plex-claim-server.sh
    mode: 0755

- name: Get plex server claim code
  uri:
    url: https://plex.tv/api/claim/token.json
    user: "{{plex.user}}"
    password: "{{plex.pass}}"
    force_basic_auth: yes
  register: plex_claim

- name: Set plex_claim_code variable
  set_fact:
    plex_claim_code: "{{plex_claim.json.token}}"

- name: Display Plex claim Token
  debug:
    msg: "Your Plex claim Token is: {{plex_claim_code}}"

- name: Launch script for Activate Plex
  raw: sudo -u plex /tmp/plex-claim-server.sh "{{plex_claim_code}}"
  notify: restart plex