---
- name: Install unzip
  package:
    name: 'unzip'
    state: latest
  
- name: "Download plexdrive"
  get_url:
    url: https://github.com/dweidenfeld/plexdrive/releases/download/5.0.0/plexdrive-linux-amd64
    dest: /usr/bin/plexdrive
    owner: root
    group: root
    mode: 0755
       
- name: Import plexdrive.service
  template:
    src: plexdrive.service.j2
    dest: /etc/systemd/system/plexdrive.service
    force: yes

- name: Create plexdrive directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /home/{{user}}/.config/plexdrive

- name: Start plexdrive service
  systemd: 
    enabled: no
    name: plexdrive 
    daemon_reload: yes 