---
# defaults file for kibatic.traefik
traefik_install_dir: /usr/bin
traefik_binary_url: https://github.com/containous/traefik/releases/download/{{traefik_version}}/traefik_linux-amd64
traefik_bin_path: "{{ traefik_install_dir }}/traefik"
traefik_config_file: /etc/traefik.toml
traefik_template: traefik.toml
traefik_systemd_unit_template: traefik.service
traefik_systemd_unit_dest: /etc/systemd/system/traefik.service
traefik_update: yes
traefik_version: v1.6.6


traefik_config:
  - name: "traefik"
    backend: "http://127.0.0.1:8080"
    url: "traefik.{{ domain }}"
  
  - name: "radarr"
    backend: "http://127.0.0.1:7878"
    url: "radarr.{{ domain }}"

  - name: "sonarr"
    backend: "http://127.0.0.1:8989"
    url: "sonarr.{{ domain }}"
  
  - name: "jackett"
    backend: "http://127.0.0.1:9117"
    url: "jackett.{{ domain }}"

  - name: "plex"
    backend: "http://127.0.0.1:32400"
    url: "plex.{{ domain }}"
  
  - name: "transmission"
    backend: "http://127.0.0.1:9091"
    url: "transmission.{{ domain }}"

