---
# ufw_rules:
#   - { [port: ""] [rule: allow] [proto: any] [from_ip: any] [to_ip: any] }
# ufw_applications:
#   - { name: OpenSSH [rule: allow, from_ip: any] }
#

# package name (version)
# depricated: `ufw_package` will be removed in future releases! Use `ufw_packages`
ufw_package: ufw
# added to support systems where ufw packages are split up
ufw_packages:
  - "{{ ufw_package }}"
# list of rules
# ufw_rules: [{ port: 22, rule: allow }]
# list of profiles located in /etc/ufw/applications.d
ufw_applications: []
# /etc/defaut/ufw settings
ufw_ipv6: "yes"
ufw_default_input_policy: DROP
ufw_default_output_policy: ACCEPT
ufw_default_forward_policy: DROP
ufw_default_application_policy: SKIP
# firewall state: enabled | disabled
ufw_state: enabled
ufw_logging: "off"
# always reset the firewall
ufw_reset: yes

ufw_rules: [
  { port: 22, rule: allow },
  { port: 80, rule: allow },
  { port: 443, rule: allow },
  { port: 32400, rule: allow },
  { port: 1900, rule: allow },
  { port: 3005, rule: allow },
  { port: 32410, rule: allow },
  { port: 32412, rule: allow },
  { port: 32413, rule: allow },
  { port: 32414, rule: allow },
  { port: 32469, rule: allow }
]