---
- name: Check if jackett version exists in /opt     
  stat: 
    path: "/opt/jackett/{{ jackett_version }}"
  register: jackett_install_location

- file:
    path: "/opt/jackett/{{ jackett_version }}"
    state: directory
    mode: 0755
  when: not jackett_install_location.stat.exists

- name: "download Jackett archive file"
  unarchive:
    src: "https://github.com/Jackett/Jackett/releases/download/{{ jackett_version }}/Jackett.Binaries.Mono.tar.gz"
    dest: "/opt/jackett/{{ jackett_version }}"
    remote_src: True
  when: not jackett_install_location.stat.exists

- name: "Add apt key for mono 5"
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: "adding repo for mono5"
  apt_repository:
    repo: deb http://download.mono-project.com/repo/ubuntu xenial main
    state: present

- name: Only run apt-get update if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install packages
  apt:
    state: latest
    name: "{{ item }}"
  with_items: "{{ jackett_packages }}"

- name: check for systemd
  command: systemctl --version
  register: jackett_systemctl_version
  ignore_errors: yes

- name: add jackett.service
  template:
    src: jackett.service.ini
    dest: /lib/systemd/system/jackett.service
    mode: 0644
  become: yes
  when: jackett_systemctl_version.rc == 0
  notify:
    - jackett_reload_systemd
    - restart_jackett

- name: create configuration directory
  file:
    path: /home/{{ user }}/.config/Jackett/Indexers
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ user }}"

- name: move indexers into place
  copy:
    src: "{{ jackett_indexer_path }}"
    dest: /home/{{ user }}/.config/Jackett/Indexers
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"
  when: jackett_load_indexers
  notify:
      - restart_jackett

- name: create configurations
  template:
    src: ServerConfig.json
    dest: /home/{{ user }}/.config/Jackett/ServerConfig-ansible.json
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"
  become: yes

- name: move new config into place
  copy:
    src: /home/{{ user }}/.config/Jackett/ServerConfig-ansible.json
    dest: /home/{{ user }}/.config/Jackett/ServerConfig.json
    remote_src: yes
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"
  notify:
    - restart_jackett

- name: remove temp file
  file:
    path: /home/{{ user }}/.config/Jackett/ServerConfig-ansible.json
    state: absent